# Generated by Django 6.0.5 on 2026-05-07 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('group', models.CharField(choices=[('A', 'группа A'), ('B', 'группа B'), ('C', 'группа C'), ('D', 'группа D'), ('GENERAL', 'Общая')], default='GENERAL', max_length=20, verbose_name='группа')),
            ],
            options={
                'verbose_name': 'позиция',
                'verbose_name_plural': 'позиции',
            },
        ),
        migrations.CreateModel(
            name='Manometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_verification_date', models.DateField(verbose_name='дата следующей поверки')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='серийный номер')),
                ('scale', models.CharField(max_length=30, verbose_name='шкала')),
                ('unit', models.CharField(max_length=25, verbose_name='единица измерения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='примечания')),
                ('is_working', models.BooleanField(default=True, verbose_name='статус исправности')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manometers', to='manometers.position', to_field='name', verbose_name='позиция')),
            ],
            options={
                'verbose_name': 'манометр',
                'verbose_name_plural': 'манометры',
            },
        ),
        migrations.CreateModel(
            name='Thermometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_verification_date', models.DateField(verbose_name='дата следующей поверки')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='серийный номер')),
                ('scale', models.CharField(max_length=30, verbose_name='шкала')),
                ('unit', models.CharField(default='°C', max_length=25, verbose_name='единица измерения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='примечания')),
                ('is_working', models.BooleanField(default=True, verbose_name='статус исправности')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thermometers', to='manometers.position', to_field='name', verbose_name='позиция')),
            ],
            options={
                'verbose_name': 'термометр',
                'verbose_name_plural': 'термометры',
            },
        ),
    ]
