# Generated by Django 6.0.5 on 2026-05-07 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manometers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manometer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manometers', to=settings.AUTH_USER_MODEL, verbose_name='подразделение'),
        ),
        migrations.AddField(
            model_name='position',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to=settings.AUTH_USER_MODEL, verbose_name='подразделение'),
        ),
        migrations.AddField(
            model_name='manometer',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manometers', to='manometers.position', to_field='name', verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='thermometer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thermometers', to=settings.AUTH_USER_MODEL, verbose_name='подразделение'),
        ),
        migrations.AddField(
            model_name='thermometer',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thermometers', to='manometers.position', to_field='name', verbose_name='позиция'),
        ),
    ]
