# Generated by Django 6.0.5 on 2026-05-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'бригада',
                'verbose_name_plural': 'бригады',
            },
        ),
        migrations.CreateModel(
            name='BrigadeTerritoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'принадлежность',
                'verbose_name_plural': 'принадлежности',
            },
        ),
        migrations.CreateModel(
            name='Manometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_verification_date', models.DateField(verbose_name='дата следующей поверки')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='заводской номер')),
                ('scale', models.CharField(max_length=255, verbose_name='шкала измерения')),
                ('unit', models.CharField(max_length=50, verbose_name='единица измерения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='примечания')),
                ('is_working', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('device_type', models.CharField(choices=[('manometer', 'манометр'), ('thermometer', 'термометр')], max_length=20, verbose_name='тип позиции')),
            ],
            options={
                'verbose_name': 'позиция',
                'verbose_name_plural': 'позиции',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'подразделение',
                'verbose_name_plural': 'подразделения',
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('territory_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('GENERAL', 'Общая')], max_length=20)),
            ],
            options={
                'verbose_name': 'территория',
                'verbose_name_plural': 'территории',
            },
        ),
        migrations.CreateModel(
            name='Thermometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_verification_date', models.DateField(verbose_name='дата следующей поверки')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='заводской номер')),
                ('scale', models.CharField(max_length=255, verbose_name='шкала измерения')),
                ('unit', models.CharField(max_length=50, verbose_name='единица измерения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='примечания')),
                ('is_working', models.BooleanField(default=True)),
            ],
        ),
    ]
