# Generated by Django 6.0.5 on 2026-05-17 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brigade',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brigadeterritoryassignment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brigadeterritoryassignment',
            name='brigade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory_assignments', to='measurement.brigade', verbose_name='бригада'),
        ),
        migrations.AddField(
            model_name='manometer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='комплекс'),
        ),
        migrations.AddField(
            model_name='position',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manometer',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manometers', to='measurement.position', verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='measurement.subdivision', verbose_name='подразделение'),
        ),
        migrations.AddField(
            model_name='manometer',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manometers', to='measurement.subdivision', verbose_name='подразделение'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brigades', to='measurement.subdivision'),
        ),
        migrations.AddField(
            model_name='territory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='territory',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='measurement.subdivision'),
        ),
        migrations.AddField(
            model_name='position',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='measurement.territory', verbose_name='территория'),
        ),
        migrations.AddField(
            model_name='brigadeterritoryassignment',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brigade_assignments', to='measurement.territory', verbose_name='территория'),
        ),
        migrations.AddField(
            model_name='thermometer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='комплекс'),
        ),
        migrations.AddField(
            model_name='thermometer',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermometers', to='measurement.position', verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='thermometer',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermometers', to='measurement.subdivision', verbose_name='подразделение'),
        ),
    ]
